import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/utils/Navbar/Navbar";
import Footer from "@/components/custom/utils/Footer/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All weights
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.variable}`}>
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
